import pandas as pd

# Load your CSV
df = pd.read_csv('your_file.csv')

# Define the mapping
intent_mapping = {
    'weather_query': 'joy',
    'agent_annoying': 'fear',
    'agent_answer_my_question': 'anticipation/demanding',
    'agent_bad': 'fear',
    'agent_be_clever': 'anticipation/demanding',
    'agent_beautiful': 'joy',
    'agent_birth_date': 'neutral',
    'agent_boring': 'fear',
    'agent_boss': 'anticipation/demanding',
    'agent_busy': 'anticipation/demanding',
    'agent_chatbot': 'neutral',
    'agent_clever': 'joy',
    'agent_crazy': 'fear',
    'agent_fired': 'fear',
    'agent_funny': 'joy',
    'agent_good': 'joy',
    'agent_happy': 'joy',
    'agent_hungry': 'anticipation/demanding',
    'agent_marry_user': 'joy',
    'agent_my_friend': 'joy',
    'agent_occupation': 'neutral',
    'agent_origin': 'neutral',
    'agent_ready': 'anticipation/demanding',
    'agent_real': 'anticipation/demanding',
    'agent_residence': 'neutral',
    'agent_right': 'joy',
    'confirmation_yes': 'joy',
    'agent_sure': 'neutral',
    'agent_talk_to_me': 'anticipation/demanding',
    'agent_there': 'fear',
    'appraisal_bad': 'fear',
    'appraisal_good': 'joy',
    'appraisal_no_problem': 'joy',
    'appraisal_thank_you': 'joy',
    'appraisal_welcome': 'joy',
    'appraisal_well_done': 'joy',
    'confirmation_cancel': 'anticipation/demanding',
    'confirmation_no': 'fear',
    'dialog_hold_on': 'anticipation/demanding',
    'dialog_hug': 'joy',
    'dialog_i_do_not_care': 'fear',
    'dialog_sorry': 'anticipation/demanding',
    'dialogue_what_do_you_mean': 'neutral',
    'dialog_wrong': 'anticipation/demanding',
    'emotions_ha_ha': 'joy',
    'emotions_wow': 'joy',
    'greetings_bye': 'anticipation/demanding',
    'greetings_goodevening': 'joy',
    'greetings_goodmorning': 'joy',
    'greetings_goodnight': 'joy',
    'greetings_hello': 'joy',
    'greetings_how_are_you': 'neutral',
    'greetings_nice_to_meet_you': 'joy',
    'greetings_nice_to_see_you': 'joy',
    'greetings_nice_to_talk_to_you': 'joy',
    'greetings_whatsup': 'joy',
    'user_angry': 'fear',
    'user_back': 'anticipation/demanding',
    'user_bored': 'anticipation/demanding',
    'user_busy': 'anticipation/demanding',
    'user_can_not_sleep': 'anticipation/demanding',
    'user_does_not_want_to_talk': 'fear',
    'user_excited': 'joy',
    'user_going_to_bed': 'neutral',
    'user_good': 'joy',
    'user_happy': 'joy',
    'user_has_birthday': 'joy',
    'user_here': 'anticipation/demanding',
    'user_joking': 'joy',
    'user_likes_agent': 'joy',
    'user_lonely': 'fear',
    'user_looks_like': 'neutral',
    'user_loves_agent': 'joy',
    'user_misses_agent':  'fear',
    'user_needs_advice': 'anticipation/demanding',
    'user_sad': 'fear',
    'user_sleepy': 'anticipation/demanding',
    'user_testing_agent': 'neutral',
    'user_tired': 'fear',
    'user_waits': 'fear',
    'user_wants_to_see_agent_again': 'fear',
    'user_wants_to_talk': 'fear',
    'user_will_be_back': 'fear',
    'agent_acquaitance': 'neutral',
    'agent_age': 'neutral'
}

# Apply the mapping
df['intent'] = df['intent'].map(intent_mapping)

# Save the new CSV
df.to_csv('updated_file.csv', index=False)
